# action.yml
name: "Development Plexicus Runner Action"

description: 'Development Plexicus code analyzer for COVULOR cloud service'
author: 'Plexicus'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  default-owner:
    description: 'Default repository owner'
    required: false
  repo-name:
    description: 'Name of the repository'
    required: true
  branch:
    description: 'Branch name for the pull request'
    required: true
  url:
    description: 'Clone URL of the repository'
    required: true
  pr-id:
    description: 'ID of the PR to be analyzed'
    required: true
  files-path:
    description: 'Path to file containing files list for scanning'
    required: false
  workspace-path:
    description: 'Path to the repository workspace'
    required: true
outputs:
  sarif-output:
    description: 'SARIF output from the analysis'
    value: ${{ steps.run-analysis.outputs.sarif-output }}
runs:
  using: 'composite'
  steps:
    - name: Prepare Files List in Required Format
      id: prepare-files
      if: ${{ inputs.files-path }}
      shell: bash
      run: |
        jq -r '.[]' "${{ inputs.files-path }}" > files_to_analyze.txt
        echo "files_to_analyze=$(pwd)/files_to_analyze.txt" >> $GITHUB_ENV

    - name: Run PLEXALYZER Docker Analysis
      id: run-analysis
      shell: bash
      run: |
        # Construct the Docker command
        docker_command="docker run --rm \
          -v \"${{ inputs.workspace-path }}:/mounted_volumes\""

        if [ -n "${files_to_analyze}" ]; then
          docker_command+=" -v \"$files_to_analyze:/app/files_to_analyze.txt\""
        fi

        docker_command+=" plexicus/plexalyzer-dev:latest \
          /venvs/plexicus-fastapi/bin/python /app/analyze.py \
          --name \"${{ inputs.repo-name }}\" \
          --branch \"${{ inputs.branch }}\" \
          --url \"${{ inputs.url }}\" \
          --pr-id \"${{ inputs.pr-id }}\" \
          --output \"sarif\" \
          --no-progress-bar"

        if [ -n "${{ inputs.default-owner }}" ]; then
          docker_command+=" --owner \"${{ inputs.default-owner }}\""
        fi

        if [ -n "${files_to_analyze}" ]; then
          docker_command+=" --files \"/app/files_to_analyze.txt\""
        fi

        # Run docker command and capture output to file
        eval $docker_command > sarif_output.json

        # Output the SARIF content
        sarif_content=$(cat sarif_output.json)
        echo "sarif-output<<EOF" >> $GITHUB_OUTPUT
        echo "$sarif_content" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
